language: python
python: "2.7"
sudo: false
cache:
  directories:
  - eggs
env:
  matrix:
    - PLONE=4
    - PLONE=5
install:
  - sed -ie "s#plone5.cfg#plone$PLONE.cfg#" buildout.cfg
# Keep setuptools and zc.buildout the synced with buildout.cfg,
# otherwise the buildout fails due to the non newest ('-N') option
# when it wants to downgrade one of them to the pinned version.
  - python bootstrap.py -c travis.cfg --buildout-version=2.5.0 --setuptools-version=19.4
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/test-coverage
  - pip install -q coveralls
  - coveralls
