language: python
python: "2.7"
sudo: false
cache:
  directories:
  - eggs
install:
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script: bin/test
after_success:
  - bin/code-analysis
  - bin/createcoverage run bin/alltests
  - pip install -q coveralls
  - coveralls

