language: python
python: "2.7"
sudo: false
cache:
  directories:
  - eggs
env:
  matrix:
    - PLONE=4
    - PLONE=5
install:
  - sed -ie "s#plone5.cfg#plone$PLONE.cfg#" buildout.cfg
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test-coverage
after_success:
  - pip install -q coveralls
  - coveralls
